/// THIS FILE IS GENERATED BY r_resources. DO NOT MODIFY MANUALLY.

// ignore_for_file: avoid_classes_with_only_static_members,always_specify_types,lines_longer_than_80_chars,non_constant_identifier_names,prefer_double_quotes,unnecessary_raw_strings,use_raw_strings


class R {
  static const images = _ImageResources();
  static const svg = _SvgResources();
}

class _ImageResources {
  const _ImageResources();
}

class _SvgResources {
  const _SvgResources();

  /// ![](/Volumes/Data/Workspace/Flutter/employee_app/assets/svg/no_employee_found.svg)
  final no_employee_found = r'assets/svg/no_employee_found.svg';

  /// ![](/Volumes/Data/Workspace/Flutter/employee_app/assets/svg/calendar.svg)
  final calendar = r'assets/svg/calendar.svg';

  /// ![](/Volumes/Data/Workspace/Flutter/employee_app/assets/svg/arrow_forward.svg)
  final arrow_forward = r'assets/svg/arrow_forward.svg';

  /// ![](/Volumes/Data/Workspace/Flutter/employee_app/assets/svg/employee.svg)
  final employee = r'assets/svg/employee.svg';

  /// ![](/Volumes/Data/Workspace/Flutter/employee_app/assets/svg/select_role.svg)
  final select_role = r'assets/svg/select_role.svg';
}
