name: Android Release

on:
  workflow_dispatch:
  
jobs:
  build:
    # runs-on: ubuntu-latest
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "11"
          cache: 'gradle'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.13.9"
          channel: 'stable'
          cache: true
      - name: Get dependencies
        run: flutter pub get
      - name: Generate translation strings
        run: flutter pub run slang
      - name: Generate required classes
        run: flutter packages pub run build_runner build -d
      - name: Start release build
        run: flutter build appbundle
